# Generated by Django 3.2 on 2021-04-29 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_rename_text_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveIntegerField(choices=[(0, '_______'), (1, '1 - Terrible'), (2, '2 - Poor'), (3, '3 - Average'), (4, '4 - Good'), (5, '5 - High')], default=0),
        ),
    ]
